homeassistant: false
frontend: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: info
  log_output:
    - console
  network_key: '!secret.yaml network_key'  
  pan_id: GENERATE
  ext_pan_id: GENERATE
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false 
device_options:
  legacy: false
# join devices via the front-end
permit_join: false
